# Generated by Django 3.2.9 on 2021-12-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=300),
        ),
    ]
