# Generated by Django 3.2.9 on 2021-11-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.UUIDField(default='F657C34D07544D7E90F954764E087CE1', editable=False, unique=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('date_activated', models.DateField(auto_now=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
