# Generated by Django 3.2.9 on 2021-11-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_number',
            field=models.UUIDField(default='46AC3B038D65456A9981BBE0CC6B2C23', editable=False, unique=True),
        ),
    ]
