# Generated by Django 3.2.9 on 2021-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_number',
            field=models.UUIDField(default='3F7F18A99C2E46E596BC26078D35F20B', editable=False, unique=True),
        ),
    ]
