# Generated by Django 3.2.9 on 2021-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_membership_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_number',
            field=models.UUIDField(default='B7C8A3B9', editable=False, unique=True),
        ),
    ]
