# Generated by Django 3.2.9 on 2021-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_alter_membership_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_number',
            field=models.UUIDField(default='D13FADF5', editable=False, unique=True),
        ),
    ]
